quickbuild:
  restart: always
  hostname: drcis-qb
  image: ashumkin/quickbuild:${QB_VERSION}
  ports:
    - "${QB_PORT}:8810"
  volumes:
    - qb-data-workspace:/var/qb/workspace
    - ${QB_STORAGE_VOLUME}:/var/qb/storage
    - qb-data-backups:/var/qb/backups
    - ${QB_BACKUP_TO_RESTORE}:/var/qb/backup-to-restore.bak:ro
  links:
    - qb-database
qb-database:
  restart: always
  image: mariadb
  command: /docker-entrypoint.sh --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
  environment:
    MYSQL_DATABASE: quickbuild
    MYSQL_ROOT_PASSWORD: mysqlroot
    MYSQL_USER: qb
    MYSQL_PASSWORD: qba
    MYSQL_BACKUP_DIR: /backup
  volumes:
    - ${QB_DB_DIR}:/var/lib/mysql
    - db-backups:/backup
