version: "3"

services:
    quickbuild:
      restart: always
      hostname: ${QB_HOSTNAME}
      image: rarus/quickbuild:${QB_VERSION}
      ports:
        - "${QB_PORT}:8810"
      volumes:
        - ./hibernate.properties:/opt/quickbuild/conf/hibernate.properties
        - ./attributes.properties:/opt/quickbuild/conf/attributes.properties
        - ${QB_WORKSPACE_VOLUME}:/var/qb/workspace
        - ${QB_STORAGE_VOLUME}:/var/qb/storage
        - qb-data-backups:/var/qb/backups
        - ${QB_BACKUP_TO_RESTORE}:/var/qb/backup-to-restore.bak:ro
        - ${QB_SSH_CONFIG}:/root/.ssh/config
      links:
        - qb-database

    qb-database:
      restart: always
      image: mariadb
      command: /docker-entrypoint.sh --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
      env_file:
        - database.env
      volumes:
        - ${QB_DB_DIR}:/var/lib/mysql
        - db-backups:/backup
